### ISSUE TITLE
Collections deprecated on Python 3.10

### ISSUE THREAD

**Issue by notluquis** [asteca/ASteCA#547]
Hi,

due to the deprecation of Collections on Python 3.10, ASTECA won't compile on the first run.

Here is the error.

`ImportError: cannot import name 'Iterable' from 'collections' (/Users/notluquis/opt/anaconda3/envs/spyder-env/lib/python3.10/collections/__init__.py)`

Iterable can be imported from collections.abc, but the other modules won't. (at least on my try of change the code)

**Comment by Gabriel-p** [comment]
Hi, yes I see that was moved in v3.10. Have you tried editing the file `ASteCA/packages/aux_funcs.py` which is where the import is done? If so, what is the full error that you get?

A perhaps simpler solution would be to just set up a `conda` environment with Python 3.9 as described here: https://asteca.readthedocs.io/en/latest/install.html

**Comment by itsluquis** [comment]
Yep, editing the file `ASteCA/packages/aux_funcs.py` is the solution.

I only change the line `fromcollections import defaultdict` to
```
from collections import defaultdict
from collections.abc import Iterable
```

In Python 3.9.12 ASteCA also works with the modification.

**Comment by Gabriel-p** [comment]
Great! I'll fix this in the next release of the code, thank you for opening the issue!

**Comment by Gabriel-p** [comment]
Re-opening so I don't forget about it :)
