### ISSUE TITLE
Import Issue for ASteCA and !pip installation Error on Google Colab

### ISSUE THREAD

**Issue by Kennyc222** [asteca/ASteCA#558]
I have tried many times, now i give up! 

May you please check the code whether it is working properly, please??

Thanks
Kenny 
![Screen Shot 2024-08-07 at 10 47 47 AM](https://github.com/user-attachments/assets/b430bc36-b395-4a8b-bf37-847cfba8bcf9)
![Screen Shot 2024-08-07 at 10 47 58 AM](https://github.com/user-attachments/assets/04f86832-0bf4-4608-808c-dfa7cee5621b)

**Comment by Gabriel-p** [comment]
Hi Kenny, this looks like an incompatibility between the versions required by `asteca` (mainly the `numpy ` version) and those required by other packages installed in Google Colab.

I've updated the developer version of the package to handle this, you can install it in Colab using:

```
!pip3 install git+https://github.com/asteca/ASteCA.git@develop
```

which will install the unreleased version `0.5.7-dev`. Let me know if this works for you

**Comment by Kennyc222** [comment]
Yeah! Your code works! Thanks so much
